package com.example.demo.constants.errorTypes;

public enum AuthErrorType {
    INVALID_CREDENTIALS,
    TOKEN_EXPIRED,
    TOKEN_INVALID,
    TOKEN_MISSING,
    ACCOUNT_LOCKED,
    ACCOUNT_DISABLED,
    SESSION_EXPIRED,
    REFRESH_TOKEN_INVALID,
    REFRESH_TOKEN_EXPIRED,
    REFRESH_TOKEN_REQUIRED,
    EMPTY_CREDENTIALS,
    AUTHENTICATION_FAILED,
    UNAUTHORIZED_ACCESS
}
